# Generated by Django 5.1.6 on 2025-02-19 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_photo_car_photo_house_photo_trendingproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quanity',
            new_name='quantity',
        ),
        migrations.AddField(
            model_name='card',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='myuser',
            name='email',
            field=models.EmailField(default='Unknown', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='first_name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='myuser',
            name='last_name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_photos', to='myapp.photo'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='phone',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
